##### Pandas continu.....
* Series(One dimensional data)

In [1]:
import pandas as pd

In [3]:
pd.Series([1,2,3,4],['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
pd.Series([[1,2,3,4],['a','b','c','d']],index=[1,2])

1    [1, 2, 3, 4]
2    [a, b, c, d]
dtype: object

#### DataFrame
* two dimensional
* collection of rows and columns

In [17]:
#using list
df=[['abc',28,'civil'],['def',40,'cse']]
df1=pd.DataFrame(df,columns=['Name','rollno','Branch'])

In [18]:
df1

Name  rollno Branch
0  abc      28  civil
1  def      40    cse

In [19]:
re1=df1.reset_index()
re1['Name']=pd.Series(({0:'abc',1:'def'}))

In [20]:
re1

index Name  rollno Branch
0      0  abc      28  civil
1      1  def      40    cse

In [52]:
#using dictionary to create a dataframe
df=pd.DataFrame([{"name":"john","Item purchased":"mobile","cost":'24K',"customer":"asfgh"},
                    {"name":"filip","Item purchased":"bike","cost":'89K'},
                    {"name":"Keyvn","Item purchased":"Books","cost":"50"}],
                    index=['store1','store2','store3'])


In [53]:
df

Item purchased cost customer   name
store1         mobile  24K    asfgh   john
store2           bike  89K      NaN  filip
store3          Books   50      NaN  Keyvn

In [40]:
#loc ----->to give index data
#iloc ----->to give index value

In [41]:
df

Item purchased cost   name
store1         mobile  24K   john
store1           bike  89K  filip
store3          Books   50  Keyvn

In [42]:
df.loc['store1']

Item purchased cost   name
store1         mobile  24K   john
store1           bike  89K  filip

In [44]:
df.iloc[0]

Item purchased    mobile
cost                 24K
name                john
Name: store1, dtype: object

In [45]:
df.iloc[2]

Item purchased    Books
cost                 50
name              Keyvn
Name: store3, dtype: object

In [46]:
df['customer']="abc1"

In [55]:
df

Item purchased cost customer   name
store1         mobile  24K    asfgh   john
store2           bike  89K      NaN  filip
store3          Books   50      NaN  Keyvn

In [54]:
df.T

store1 store2 store3
Item purchased  mobile   bike  Books
cost               24K    89K     50
customer         asfgh    NaN    NaN
name              john  filip  Keyvn

In [57]:
df.T.loc["cost"]

store1    24K
store2    89K
store3     50
Name: cost, dtype: object

In [59]:
df.T.iloc[3]

store1     john
store2    filip
store3    Keyvn
Name: name, dtype: object

In [60]:
#using function to read csv file
def Csvfile(fpath):
    return pd.read_csv(fpath)
fpath="income.csv"
Csvfile(fpath)

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [62]:
#without using function
filepath="income.csv"
income=pd.read_csv(filepath)

In [63]:
income

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [65]:
#to print all column names
#o/p: GEOID State 2005 2006 2007 2008 2009 2010 2011 2012 2013
for i in income.keys():
    print(i,end=" ")

GEOID State 2005 2006 2007 2008 2009 2010 2011 2012 2013 

In [66]:
for i in income.columns:
    print(i,end=" ")

GEOID State 2005 2006 2007 2008 2009 2010 2011 2012 2013 

In [72]:
for i in income.values:
    print(i)

['04000US01' 'Alabama' 37150 37952 42212 44476 39980 40933 42590 43464
 41381]
['04000US02' 'Alaska' 55891 56418 62993 63989 61604 57848 57431 63648
 61137]
['04000US04' 'Arizona' 45245 46657 62993 46914 45739 46896 48621 47044
 50602]
['04000US05' 'Arkansas' 36658 37057 40795 39586 36538 38587 41302 39018
 39919]
['04000US06' 'California' 51755 55319 55734 57014 56134 54283 53367 57020
 57528]


In [79]:
# Alabama:41381  .. ..


# California:57528
for i in income.values:
    print(i[1],":",i[10])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


##### Numpy
* Numpy is programming language that deals with multi-dimensional arrays and matrices
* Numerical python pr numeric python
* numpy supports a large number of mathematical operations.
###### how to install numpy 
* numpy is installed by default in anconda.

In [80]:
import numpy as np

In [81]:
print(np.__version__)

1.16.2


In [83]:
#numpy arrays
#1D array
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [85]:
print(np.array([2,4,6,8]))

[2 4 6 8]


In [86]:
#2D array
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
print(np.array([[1,2,3,4],[5,6,7,8]]))

[[1 2 3 4]
 [5 6 7 8]]


In [88]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
#mathematical operations
a1=np.array([3,5,6,7])
a2=np.array([2,4,9,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[ 5  9 15 15]
[ 1  1 -3 -1]
[ 6 20 54 56]
[1.5        1.25       0.66666667 0.875     ]


In [ ]:
data=np.array([[1,2,3,4]])