### dictionary comprehension
- short description
    - {o/p i/p sequence condition}

In [2]:
# write a program to print the vowels in the string(user/developer)
s=input()
v="aeiouAEIOU"
for ch in s:
    if ch in v:
        print(ch,end=" ")

python pROGRAM
o O A 

In [3]:
vowels={ch:ord(ch) for ch in s if ch in v}
vowels

{'o': 111, 'O': 79, 'A': 65}

### numpy and pandas
function:collection/group of statements<br>
module:collection of functions<br>
package:collection of module<br>

### data science--data analysis ,data manipulation and data cleaning
 pandas module/package

In [ ]:
numpy--array type of data
## used for scientific computation
- log,exp,variance,min(),max(),mean(),median(),vectorized,matrix operations
- math,random-->sub module(numpy)

In [6]:
'ruthu'.startswith('r')

True

In [7]:
array--{1,2}--row
2d--row & col
[list of lists]
[1 2 3 4]:row matrix
[1
 2
 3
 4]
[[1 2 3]
[4 5 6]]

SyntaxError: invalid syntax (<ipython-input-7-df69ebe1cbf8>, line 2)

In [9]:
import numpy as n
ar=n.array((1,2,3,4))
ar

array([1, 2, 3, 4])

In [11]:
ar2=n.array([1,2,3,4,5])
print(ar2)

[1 2 3 4 5]


In [15]:
ar3=n.array([[1],[2],[3]])
print(ar3)

[[1]
 [2]
 [3]]


In [17]:
ar4=n.array([[2,3,4],[7,8,9]])
ar4

array([[2, 3, 4],
       [7, 8, 9]])

In [19]:
ar5=n.array([(1,2,3),(6,7,"8")])
ar5

array([['1', '2', '3'],
       ['6', '7', '8']], dtype='<U11')

In [20]:
for num in range(1,21,5):
    print(num)

1
6
11
16


In [21]:
#21--->5
21/5

4.2

In [23]:
11/4

2.75

In [ ]:
10,11,12,13,14,15,16,17,18,19,20-->
11/4